//
// AUTO-GENERATED BY BDS GENERATOR. DO NO EDIT THIS FILE, AS CHANGES WILL BE OVERWRITTEN.
// Derived from BOM (model name 'com.example.sfc_provisioningbom').
//     

// This file is a case/global class ref implementation
package com.example.sfc_provisioningbom.si.goref.impl;

import java.net.MalformedURLException;
import java.util.List;
import com.tibco.bds.api.dto.CaseCriteriaDTO;
import com.tibco.bds.api.goref.GORef;
import com.tibco.bds.services.InternalServiceFault;
import com.tibco.bds.services.SecurityFault;
import com.tibco.bds.services.CaseDataAccessFault;
import com.tibco.bds.services.CaseDataChangedFault;
import com.tibco.bds.services.CaseModelReferenceFault;
import com.tibco.bds.services.CaseReferenceFault;
import com.tibco.bds.common.exception.BDSSIException;
import com.tibco.bds.common.si.PaginatedList;
import com.tibco.bds.common.si.exception.ApplicationError;

public class ContractorGroupsRefImpl
		extends
			com.tibco.bds.common.si.impl.RefImpl
		implements
			com.example.sfc_provisioningbom.si.goref.ContractorGroupsRef {

	private static final long serialVersionUID = 1L;

	public ContractorGroupsRefImpl(String url) throws IllegalArgumentException,
			MalformedURLException {

		super(url, com.example.sfc_provisioningbom.si.Activator
				.getBundleVersion());

	}

	public ContractorGroupsRefImpl(GORef goref) throws MalformedURLException {

		super(goref, com.example.sfc_provisioningbom.si.Activator
				.getBundleVersion());

	}

	@Override
	public com.example.sfc_provisioningbom.ContractorGroups readContractorGroups()
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, CaseReferenceFault,
			BDSSIException {
		return (com.example.sfc_provisioningbom.ContractorGroups) siService
				.readSingleCase(this);
	}

	@Override
	public com.example.sfc_provisioningbom.si.goref.ContractorGroupsRef updateContractorGroups(
			com.example.sfc_provisioningbom.ContractorGroups obj)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, CaseReferenceFault,
			CaseDataChangedFault, IllegalArgumentException,
			MalformedURLException, BDSSIException, ApplicationError {
		return (com.example.sfc_provisioningbom.si.goref.ContractorGroupsRef) siService
				.updateCaseObject(this, obj);
	}

	@Override
	public void deleteContractorGroups() throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			CaseReferenceFault, CaseDataChangedFault, BDSSIException,
			ApplicationError {
		siService.deleteCaseByRefObject(this);
	}

}
