<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:fault="http://www.tibco.com/bx/_n8imgNZ-EeevAohC3a_ghw/fault" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Case1CreateCaseData" targetNamespace="http://www.tibco.com/bx/_n8imgNZ-EeevAohC3a_ghw/fault" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="CreateCaseDataFault">
    <part name="errorCode" type="xsd:string"/>
  </message>
  <portType name="Case1CreateCaseData">
    <operation name="Case1CreateCaseData">
      <fault message="fault:CreateCaseDataFault" name="fault_NonUniqueCaseIdentifierError"/>
    </operation>
  </portType>
</definitions>
