//
// AUTO-GENERATED BY BDS GENERATOR. DO NO EDIT THIS FILE, AS CHANGES WILL BE OVERWRITTEN.
// Derived from BOM (model name 'com.example.sfc_provisioningbom').
//     

// This file is a case class service interface
package com.example.sfc_provisioningbom.da.service;

public interface ContractorGroupsService
		extends
			com.tibco.bds.common.da.service.DACommonService {
}
