<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:fault="http://www.tibco.com/bx/_kELrsOViEee0aKkJX_OoAg/fault" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SafaricomFixedInternet_SLAConfigurations_Create" targetNamespace="http://www.tibco.com/bx/_kELrsOViEee0aKkJX_OoAg/fault" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="CreateCaseDataFault">
    <part name="errorCode" type="xsd:string"/>
  </message>
  <portType name="SafaricomFixedInternet_SLAConfigurations_Create">
    <operation name="SafaricomFixedInternet_SLAConfigurations_Create">
      <fault message="fault:CreateCaseDataFault" name="fault_NonUniqueCaseIdentifierError"/>
    </operation>
  </portType>
</definitions>
