<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:fault="http://www.tibco.com/bx/_u7cgQOVOEeeRkLvTRwuu3w/fault" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SafaricomFixedInternet_SystemParameters_Update" targetNamespace="http://www.tibco.com/bx/_u7cgQOVOEeeRkLvTRwuu3w/fault" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="UpdateCaseFault">
    <part name="errorCode" type="xsd:string"/>
  </message>
  <portType name="SafaricomFixedInternet_SystemParameters_Update">
    <operation name="SafaricomFixedInternet_SystemParameters_Update">
      <fault message="fault:UpdateCaseFault" name="fault_CaseOutOfSyncError"/>
    </operation>
  </portType>
</definitions>
