//
// AUTO-GENERATED BY BDS GENERATOR. DO NO EDIT THIS FILE, AS CHANGES WILL BE OVERWRITTEN.
// Derived from BOM (model name 'com.example.sfc_provisioningbom').
//     

// This file is the SLA_Configuration Case Access Class(CAC) Implementation Class
package com.example.sfc_provisioningbom.si.cac.impl;

import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.List;

import com.tibco.bds.api.dto.CaseCriteriaDTO;
import com.tibco.bds.api.dto.util.BDSTypeConversions;
import com.tibco.bds.services.CaseDataAccessFault;
import com.tibco.bds.services.CaseDataChangedFault;
import com.tibco.bds.services.CaseModelReferenceFault;
import com.tibco.bds.services.CaseReferenceFault;
import com.tibco.bds.services.InternalServiceFault;
import com.tibco.bds.services.SecurityFault;
import com.tibco.bds.common.exception.BDSSIException;
import com.tibco.bds.common.si.PaginatedList;
import com.tibco.bds.common.si.impl.CACImpl;
import com.tibco.bds.common.si.exception.ApplicationError;

import org.eclipse.emf.ecore.EObject;

public class SLA_ConfigurationCACImpl extends CACImpl
		implements
			com.example.sfc_provisioningbom.si.cac.SLA_ConfigurationCAC {

	public SLA_ConfigurationCACImpl() {
		super(com.example.sfc_provisioningbom.si.Activator.getBundleVersion(),
				"com.example.sfc_provisioningbom.SLA_Configuration");
	}

	@Override
	public Object create(Object obj) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			IllegalArgumentException, MalformedURLException, BDSSIException,
			ApplicationError {
		return siService.createCaseObject(obj);
	}

	@SuppressWarnings("unchecked")
	public List<com.example.sfc_provisioningbom.SLA_Configuration> read(
			List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> refs)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			CaseReferenceFault, InternalServiceFault, SecurityFault,
			IllegalArgumentException, MalformedURLException, BDSSIException {
		return siService.readCase(refs);
	}

	@SuppressWarnings("unchecked")
	public List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> update(
			List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> refs,
			List<com.example.sfc_provisioningbom.SLA_Configuration> objs)
			throws CaseDataAccessFault, CaseDataChangedFault,
			CaseModelReferenceFault, CaseReferenceFault, InternalServiceFault,
			SecurityFault, IllegalArgumentException, MalformedURLException,
			BDSSIException, ApplicationError {
		return (List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef>) siService
				.updateCaseObject(refs, objs);
	}

	public void deleteRefs(
			List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> refs)
			throws CaseDataAccessFault, CaseDataChangedFault,
			CaseModelReferenceFault, CaseReferenceFault, InternalServiceFault,
			SecurityFault, IllegalArgumentException, MalformedURLException,
			BDSSIException, ApplicationError {
		siService.deleteCaseByRefObject(refs);
	}

	@Override
	@SuppressWarnings("unchecked")
	public List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> find(
			com.example.sfc_provisioningbom.SLA_Configuration obj)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException {
		return siService.findCaseByExample(obj);
	}

	@Override
	@SuppressWarnings("unchecked")
	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> find(
			com.example.sfc_provisioningbom.SLA_Configuration obj,
			Object startIndex, Object pageSize) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException {
		return siService.findCaseByExample(obj, startIndex, pageSize);
	}

	@Override
	@SuppressWarnings("unchecked")
	public List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> findAll()
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException {
		return siService.findAllCases();
	}

	@Override
	@SuppressWarnings("unchecked")
	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> findAll(
			Object startIndex, Object pageSize) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException {
		return siService.findAllCases(startIndex, pageSize);
	}

	@Override
	@SuppressWarnings("unchecked")
	public List<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> findByCriteria(
			Object criteriaOrQueryString) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException, ApplicationError {
		return siService.findCaseByCriteriaObject(criteriaOrQueryString);
	}

	@Override
	@SuppressWarnings("unchecked")
	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef> findByCriteria(
			String query, Object startIndex, Object pageSize)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException {
		return siService.findCaseByCriteria(query, startIndex, pageSize);
	}

	@Override
	public com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef findByCompositeIdentifier(
			Object SLALevel, Object taskName, Object processName)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException {
		com.example.sfc_provisioningbom.SLA_Configuration obj = com.example.sfc_provisioningbom.Sfc_provisioningbomFactory.eINSTANCE
				.createSLA_Configuration();
		obj.setSLALevel(BDSTypeConversions.convertToBigInteger(SLALevel));
		obj.setTaskName(BDSTypeConversions.convertToString(taskName));
		obj.setProcessName(BDSTypeConversions.convertToString(processName));
		return (com.example.sfc_provisioningbom.si.goref.SLA_ConfigurationRef) siService
				.findCaseByCID(obj);
	}

	@Override
	public void deleteByCompositeIdentifier(Object SLALevel, Object taskName,
			Object processName) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			CaseReferenceFault, CaseDataChangedFault, BDSSIException,
			ApplicationError {
		com.example.sfc_provisioningbom.SLA_Configuration obj = com.example.sfc_provisioningbom.Sfc_provisioningbomFactory.eINSTANCE
				.createSLA_Configuration();
		obj.setSLALevel(BDSTypeConversions.convertToBigInteger(SLALevel));
		obj.setTaskName(BDSTypeConversions.convertToString(taskName));
		obj.setProcessName(BDSTypeConversions.convertToString(processName));
		siService.deleteCaseByCID(obj);
	}

}
