<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:fault="http://www.tibco.com/bx/_k_rU8Ni8Eeeq5YfzBECo3g/fault" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Case1UpdateCaseData" targetNamespace="http://www.tibco.com/bx/_k_rU8Ni8Eeeq5YfzBECo3g/fault" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="UpdateCaseFault">
    <part name="errorCode" type="xsd:string"/>
  </message>
  <portType name="Case1UpdateCaseData">
    <operation name="Case1UpdateCaseData">
      <fault message="fault:UpdateCaseFault" name="fault_CaseOutOfSyncError"/>
    </operation>
  </portType>
</definitions>
