<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns:fault="http://www.tibco.com/bx/_LV71QPETEeeJiLkPq4yokA/fault" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ContractorGroupsCreateCaseData" targetNamespace="http://www.tibco.com/bx/_LV71QPETEeeJiLkPq4yokA/fault" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <message name="CreateCaseDataFault">
    <part name="errorCode" type="xsd:string"/>
  </message>
  <portType name="ContractorGroupsCreateCaseData">
    <operation name="ContractorGroupsCreateCaseData">
      <fault message="fault:CreateCaseDataFault" name="fault_NonUniqueCaseIdentifierError"/>
    </operation>
  </portType>
</definitions>
