//
// AUTO-GENERATED BY BDS GENERATOR. DO NO EDIT THIS FILE, AS CHANGES WILL BE OVERWRITTEN.
// Derived from BOM (model name 'com.example.sfc_provisioningbom').
//     

// This file is the SystemParameters Case Access Class (CAC)
package com.example.sfc_provisioningbom.si.cac;

import java.net.MalformedURLException;
import java.util.List;
import com.tibco.bds.services.CaseDataAccessFault;
import com.tibco.bds.services.CaseDataChangedFault;
import com.tibco.bds.services.CaseModelReferenceFault;
import com.tibco.bds.services.CaseReferenceFault;
import com.tibco.bds.services.InternalServiceFault;
import com.tibco.bds.services.SecurityFault;
import com.tibco.bds.common.exception.BDSSIException;
import com.tibco.bds.common.si.CAC;
import com.tibco.bds.common.si.PaginatedList;
import com.tibco.bds.common.si.exception.ApplicationError;
import com.tibco.bds.api.dto.CaseCriteriaDTO;

public interface SystemParametersCAC extends CAC {

	public Object create(Object obj) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			IllegalArgumentException, MalformedURLException, BDSSIException,
			ApplicationError;

	public List<com.example.sfc_provisioningbom.SystemParameters> read(
			List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> refs)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			CaseReferenceFault, InternalServiceFault, SecurityFault,
			IllegalArgumentException, MalformedURLException, BDSSIException;

	public List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> update(
			List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> refs,
			List<com.example.sfc_provisioningbom.SystemParameters> objs)
			throws CaseDataAccessFault, CaseDataChangedFault,
			CaseModelReferenceFault, CaseReferenceFault, InternalServiceFault,
			SecurityFault, IllegalArgumentException, MalformedURLException,
			BDSSIException, ApplicationError;

	public void deleteRefs(
			List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> refs)
			throws CaseDataAccessFault, CaseDataChangedFault,
			CaseModelReferenceFault, CaseReferenceFault, InternalServiceFault,
			SecurityFault, IllegalArgumentException, MalformedURLException,
			BDSSIException, ApplicationError;

	public com.example.sfc_provisioningbom.si.goref.SystemParametersRef findByPropertyName(
			Object id) throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException;

	public List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> find(
			com.example.sfc_provisioningbom.SystemParameters obj)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException;

	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> find(
			com.example.sfc_provisioningbom.SystemParameters obj,
			Object startIndex, Object pageSize) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException;

	public List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> findAll()
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException;

	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> findAll(
			Object startIndex, Object pageSize) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException;

	public List<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> findByCriteria(
			Object criteriaOrQueryString) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			BDSSIException, ApplicationError;

	public PaginatedList<com.example.sfc_provisioningbom.si.goref.SystemParametersRef> findByCriteria(
			String query, Object startIndex, Object pageSize)
			throws CaseDataAccessFault, CaseModelReferenceFault,
			InternalServiceFault, SecurityFault, BDSSIException;

	public void deleteByPropertyName(Object id) throws CaseDataAccessFault,
			CaseModelReferenceFault, InternalServiceFault, SecurityFault,
			CaseReferenceFault, CaseDataChangedFault, BDSSIException,
			ApplicationError;

}
